### ISSUE TITLE
Error:    locate template: Template file 'fsimilar_plain.tmpl' not found

### ISSUE THREAD

**Issue by hippypink** [go-dedup/fsimilar#1]
Running from binary on Debian.
I have a folder with about 1000 files to compare. Folder is called '1'

find 1 | fsimilar sim -v -i 

This returns the error:

locate template: Template file 'fsimilar_plain.tmpl' not found

**Comment by hippypink** [comment]
if I copy that template file to where I ran the command, then if fixes it. Clunky, but works

**Comment by suntong** [comment]
I've actually thought about it before, let me check ... 

Found it, 

https://github.com/go-dedup/fsimilar/blob/6653eab22f21eb09e23aa96a04addc4f03aa679f/template.go#L83-L98

It actually looks into three different places for the config files, fiirst being the path to the executable itself.
